version: "3.8"

services:
  promojio-server:
    image: ashleykoh24/promojio-server
    container_name: promojio-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_started

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=pass

volumes:
  data: {}

networks:
  default:
    name: mongodb_network
